# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

conda:
  environment: environment.yml

# Set the OS, Python version, and other tools you might need
build:
  os: ubuntu-24.04
  tools:
    python: "mambaforge-22.9"
  jobs:
    build:
      html:
        - conda install -c nvidia cuda-compiler cuda-libraries-dev
        - mkdir build && cd build cmake .. -GNinja -DWITH_CUDA=YES -DISCE3_FETCH_DEPS=NO -DCMAKE_INSTALL_PREFIX=./install
        - cd build && ninja install
    post_build:
      - mkdir -p $READTHEDOCS_OUTPUT/html/api
      - doxygen doc/doxygen/Doxyfile.in
      - mv docs-output $READTHEDOCS_OUTPUT/html/api/cxx
    pre_install:
      - pip install mkdocs-material

mkdocs:
  configuration: mkdocs.yml
